config/routes.rb
Rails.application.routes.draw do
  resources :orders
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :products
  get 'categories/index'
  get 'categories/edit'
  get 'categories/new'
  get 'categories/show'
  get 'home/index'
    resources :posts
    resources :categories
  root :to => 'home#index'
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    #attr_acessible :name
    has_many :posts
end

app/models/order.rb
class Order < ApplicationRecord
    has_one :product
end

app/models/post.rb
class Post < ApplicationRecord
    #attr_acessible :title, :body, :category_id, :author_id
    belongs_to :category
end

app/models/product.rb
class Product < ApplicationRecord
    has_many_attached :images
    #belongs_to :order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  def show
    @category = Category.find(params[:id])
    @title = @category.name
    @posts = @category.posts
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base

  def create
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.save
        ApplicationMailer.order_email(@order).deliver
        format.html { redirect_to(root_path, notice: 'Order was successfully created.') }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def order_params
      params.require(:order).permit(:name, :email, :phone, :product_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index 
        @posts = Post.all
    end
    def show 
        @post = Post.find(params[:id])
    end
    def new 
        @post = Post.new
        @category = Category.all
    end
    def create 
        @post = Post.new(post_params)
        if @post.save
            redirect_to posts_path, :notice => "Your post has been saved"
        else
            render "new"
        end
    end
    def post_params
        params.require(:post).permit(:title, :body, :category_id)
    end
    def edit 
        @post = Post.find(params[:id])
    end
    def update 
        @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
            redirect_to post_path, :notice => "Your post has been updated"
        else
            render "edit"
        end
    end
    def destroy 
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path, :notice => "Your post has been deleted"
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @order = Order.new
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>
<ul>
<% @categories.each do |category| %>
    <li><%= link_to category.name, category %></li>
<% end %>
</ul>

app/views/categories/show.html.erb
<h1> <%= @category.name %> </h1>
<%= if @posts.each do |post| %>
    <h3> <%= link_to post.title, post %> </h3>
    <p> <%= post.body %> </p>
<% end.empty? %>
    <p> Sorry, there are no posts in this category </p>
<% end %>
<%= link_to "Back to Categories", categories_path %> 

app/views/home/index.html.slim
div
  div id="carousel" class="carousel slide carousel-fade" data-ride="carousel" data-interval="6000"
    ol class="carousel-indicators"
      li data-target="#carousel" data-slide-to="0" class="active"
      li data-target="#carousel" data-slide-to="1"
      li data-target="#carousel" data-slide-to="2"
    div class="carousel-inner" role="listbox"
        div class="carousel-item active"
          a href="https://bootstrapcreative.com/"
            picture
              source srcset="https://dummyimage.com/2000x500/007aeb/4196e5" media="(min-width: 1400px)"
              source srcset="https://dummyimage.com/1400x500/#007aeb/4196e5" media="(min-width: 769px)"
              source srcset="https://dummyimage.com/800x500/007aeb/4196e5" media="(min-width: 577px)"
              img srcset="https://dummyimage.com/600x500/007aeb/4196e5" alt="responsive image" class="d-block img-fluid"

              div class="carousel-caption"
                div
                  h2 Digital Craftsmanship
                  p We meticously build each site to get results
                  span class="btn btn-sm btn-outline-secondary" Learn More
                        
        div class="carousel-item"
          a href="https://bootstrapcreative.com/"
            picture
              source srcset="https://dummyimage.com/2000x500/007aeb/4196e5" media="(min-width: 1400px)"
              source srcset="https://dummyimage.com/1400x500/007aeb/4196e5" media="(min-width: 769px)"
              source srcset="https://dummyimage.com/800x500/007aeb/4196e5" media="(min-width: 577px)"
              img srcset="https://dummyimage.com/600x500/007aeb/4196e5" alt="responsive image" class="d-block img-fluid"
                
              div class="carousel-caption justify-content-center align-items-center"
                div
                  h2 Every project begins with a sketch
                  p We work as an extension of your business to explore solutions
                  span class="btn btn-sm btn-outline-secondary" Our Process

        div class="carousel-item"
          a href="https://bootstrapcreative.com/"
            picture>
              source srcset="https://dummyimage.com/2000x500/007aeb/4196e5" media="(min-width: 1400px)"
              source srcset="https://dummyimage.com/1400x500/007aeb/4196e5" media="(min-width: 769px)"
              source srcset="https://dummyimage.com/800x500/007aeb/4196e5" media="(min-width: 577px)"
              img srcset="https://dummyimage.com/600x500/007aeb/4196e5" alt="responsive image" class="d-block img-fluid"
              
              div class="carousel-caption justify-content-center align-items-center"
                div
                  h2 Performance Optimization
                  p We monitor and optimize your site's long-term performance
                  span class="btn btn-sm btn-secondary" Learn How
                      
    a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev"
      span class="carousel-control-prev-icon" aria-hidden="true"
      span class="sr-only" Previous
        
    a class="carousel-control-next" href="#carousel" role="button" data-slide="next"
      span class="carousel-control-next-icon" aria-hidden="true">
      span class="sr-only" Next
    
  div class="container" id="content"
    - if (notice != nil)
      p id="notice" class="alert alert-success" = notice
    div class="row"
      - @products.each do |product|
        div class="col-lg-4 col-md-6 mb-4"
          div class="card h-100"
            a 
            =link_to product
              - unless product.images.empty?
                img =image_tag(product.images.first, class: "card-img-top") 
              - else
                img =image_tag("confused.png", class: "card-img-top") 
            div class="card-body"
              h4 class="card-title"
                a
                =link_to product
                  = product.name
              h5 
                |$
                = product.price
              p class="card-text" 
                = product.description
            div class="card-footer"
              small class="text-muted"
                | &#9733; &#9733; &#9733; &#9733; &#9734;

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.1.slim
doctype html
html
  head
    title MinionStore
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top"
        div class="container"
            a class="navbar-brand" href="#"
                img src="http://placehold.it/300x60?text=Logo" width="150" height="30" alt=""
            button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"
                span class="navbar-toggler-icon"
            div class="collapse navbar-collapse" id="navbarResponsive"
                ul class="navbar-nav ml-auto"
                    li class="nav-item active"
                        a class="nav-link"
                            | Home
                    li class="nav-item"
                        a class="nav-link"
                            | About
                    li class="nav-item"
                        a class="nav-link"
                            | Services
                    li class="nav-item"
                        a class="nav-link"
                            | Contact

    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title MinionStore
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav class="navbar navbar-expand-lg navbar-dark fixed-top"
        div class="container"
            button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"
                span class="navbar-toggler-icon"
            div class="collapse navbar-collapse" id="navbarResponsive"
                ul class="navbar-nav mr-auto"
                    li class="nav-item active"
                        a class="nav-link"
                            | Home
                    li class="nav-item"
                        a class="nav-link"
                            | About
                    li class="nav-item"
                        a class="nav-link"
                            | Services
                    li class="nav-item"
                        a class="nav-link"
                            | Contact
            form class="form-inline my-2 my-lg-0"
                input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"
                button class="btn btn-outline-light my-2 my-sm-0" type="submit" Search
    
    div id="eye-div"
        img =image_tag("eye.png", class: "eye") 

    = yield


footer class="py-5 bg-dark"
  div class="container"
    p class="m-0 text-center text-white" Copyright &copy; Wagner Sodré 2018

app/views/orders/_form.html.slim
= semantic_form_for @order do |f| 
  = f.inputs do
    = f.input :name
    = f.input :email
    = f.input :phone
    = f.select :product_id, Product.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"} 
  end

  = f.actions do 
    = f.action :submit, :as => :input
  end
end

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.email %></td>
        <td><%= order.phone %></td>
        <td><%= order.product_id %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @order.phone %>
</p>

<p>
  <strong>Product:</strong>
  <%= @order.product_id %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>
<%= form_for @post do |f| %>
    <p>
        <%= f.label :title %> <br/>
        <%= f.text_field :title %> <br/>
    </p>
    <p>
        <%= f.label :body %> <br/>
        <%= f.text_area :body %> <br/>
    </p>
    <p>
        <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"} %> <br/>
    </p>
    <p>
        <%= f.submit "Update Post" %> <br/>
    </p>
<% end %>

<%= link_to "Go Back", post_path %> 

app/views/posts/index.html.erb
<h1> Blog Posts </h1>

<% @posts.each do |post| %>
    <h3> <%= link_to post.title, post %> </h3>
    <p> <%= post.body %> <p>
    <hr>
<% end %>

<%= link_to "Add New Post", new_post_path %> 

app/views/posts/new.html.erb
<h1> Add new Posts </h1>
<%= form_for @post do |f| %>
    <p>
        <%= f.label :title %> <br/>
        <%= f.text_field :title %> <br/>
    </p>
    <p>
        <%= f.label :body %> <br/>
        <%= f.text_area :body %> <br/>
    </p>
    <p>
        <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"} %> <br/>
    </p>
    <p>
        <%= f.submit "Add Post" %> <br/>
    </p>
<% end %>

app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>
<small> <%= @post.created_at.strftime("%b %d. %y ") %> </small>
<p> <%= @post.body %> </p>

<p> Category: <%= link_to @post.category.name, category_path(:id => @post.category.id) %> </p> 

<%= link_to "Back", posts_path %> 

<% if false %>
<%= link_to "Edit Post", edit_post_path %> | <%= link_to "Delete", @post,  data: { confirm: "Are you sure you want to delete this post?"}, :method => :delete  %>
<% end %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.stock %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.slim
div
  div class="container" id="product-page"
    div class="row"
      div class="col-8"
        - if @product.images.present?
          div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel"
            div class="carousel-inner"
              div class="carousel-item active"
                img =image_tag(@product.images.first, class: "d-block w-100", size: "100x600")
              - @product.images.each do |image|
                  - if @product.images.first != image
                    div class="carousel-item"
                      img =image_tag(image, class: "d-block w-100", size: "100x600")
            a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev"
              span class="carousel-control-prev-icon" aria-hidden="true"
              span class="sr-only" Previous
            a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next"
              span class="carousel-control-next-icon" aria-hidden="true"
              span class="sr-only" Next
        - else
          img =image_tag("confused.png", class: "d-block w-100", size: "100x600") 
      div class="col-4" id="details"
        h1
          = @product.name
        h3 
          = @product.price
        p class="card-text" 
          = @product.description
        hr
        = semantic_form_for @order do |f| 
          = f.inputs do
            = f.input :name, :as => :string
            = f.input :email, :as => :email
            = f.input :phone, :as => :phone
            = f.input :product_id, :as => :hidden, :input_html => { :value => @product.id }
          end

          = f.actions do 
            = f.action :submit, :as => :input
          end
        end